version: "3.8"

services:
  postgres:
    image: postgres:17.4
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: yobi
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}

  backend:
    image: be-spring-image
    container_name: be-spring-container
    build:
      context: ./BE
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      TZ: ${TZ}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - postgres
      - redis

  ocr:
    image: ocr-app
    container_name: ocr-app
    build:
      context: ./OCR
    ports:
      - "7000:7000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      API_TITLE: ${API_TITLE}
      API_DESCRIPTION: ${API_DESCRIPTION}
      API_VERSION: ${API_VERSION}

volumes:
  postgres_data:
