version: "3.8"

services:
  postgres:
    image: postgres:17.4
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    image: be-spring-image
    container_name: be-spring-container
    build:
      context: ./BE
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      TZ: ${TZ}
    depends_on:
      - postgres
      - redis

  ocr:
    image: ocr-app
    container_name: ocr-app
    build:
      context: ./OCR
    ports:
      - "7000:7000"
    depends_on:
      - postgres

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  postgres_data:
  jenkins_home:
