version: "3.8"

services:
  ai:
    image: ai-app
    container_name: ai-app
    build:
      context: ./AI
    ports:
      - "6000:6000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${EC2_1_IP}:5432/${POSTGRES_DB}
      REDIS_HOST: ${EC2_1_IP}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_KEY_ID: ${AWS_SECRET_KEY_ID}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
    networks:
      - yobi-network

networks:
  yobi-network:
    driver: bridge
