version: "3.8"

services:
  ai:
    image: ai-app
    container_name: ai-app
    build:
      context: ./AI
    ports:
      - "6000:6000"
    environment:
      DATABASE_URL: ${DATABASE_URL} # AI에서 사용할 DATABASE_URL 설정
      REDIS_HOST: ${REDIS_HOST} # AI에서 사용할 REDIS_HOST 설정
      REDIS_PORT: ${REDIS_PORT} # AI에서 사용할 REDIS_PORT 설정
      REDIS_DB: ${REDIS_DB} # AI에서 사용할 REDIS_DB 설정
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_KEY_ID: ${AWS_SECRET_KEY_ID}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
