version: "3.8"

services:
  ai:
    image: ai-app
    container_name: ai-app
    build:
      context: ./AI
      dockerfile: Dockerfile
    restart: always
    ports:
      - "6000:6000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL} # AI에서 사용할 DATABASE_URL 설정
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_KEY_ID: ${AWS_SECRET_KEY_ID}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
