### 회원가입 테스트 (multipart/form-data)
POST http://localhost:8080/api/users
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="name"

제발요
--MyBoundary
Content-Disposition: form-data; name="employeeNumber"

321654
--MyBoundary
Content-Disposition: form-data; name="password"

ssafy123
--MyBoundary--

### 로그인 테스트
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "employeeNumber": 321654,
  "password": "ssafy123"
}

### 로그인 후 토큰으로 보호된 API 테스트
GET http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiI1IiwiZW1wbG95ZWVOdW1iZXIiOiIzMjE2NTQiLCJpYXQiOjE3NDcyMDE4MTAsImV4cCI6MTc0OTc5MzgxMH0.Q99cXys0NtzlCncTK7cVCsGcQPEaKkXTYKQvIYaSqQs


### 리프레시 토큰으로 토큰 갱신
POST http://localhost:8080/api/users/refresh
Content-Type: application/json

{

  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiI1IiwiZW1wbG95ZWVOdW1iZXIiOiIzMjE2NTQiLCJpYXQiOjE3NDcyOTUyNzMsImV4cCI6MTc0OTg4NzI3M30.liTdq6vKRbeHiFahAeaaupK-VH5qoJuu6YOeAqdfD5A"
}


### 사용자 정보 조회
GET http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiI1IiwiZW1wbG95ZWVOdW1iZXIiOiIzMjE2NTQiLCJpYXQiOjE3NDcyOTA2NDIsImV4cCI6MTc0OTg4MjY0Mn0.11a-ni6YXkMiMkmPdI3JAuhM1UVB1NIn2pBMq0ES5WU

### 로그아웃
POST http://localhost:8080/api/v1/users/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiI1IiwiZW1wbG95ZWVOdW1iZXIiOiIzMjE2NTQiLCJpYXQiOjE3NDcyOTUyNzMsImV4cCI6MTc0OTg4NzI3M30.liTdq6vKRbeHiFahAeaaupK-VH5qoJuu6YOeAqdfD5A
Content-Type: application/json

