### 회원가입 테스트 (multipart/form-data)
POST http://localhost:8080/api/users
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="name"

제발요
--MyBoundary
Content-Disposition: form-data; name="employeeNumber"

321654
--MyBoundary
Content-Disposition: form-data; name="password"

ssafy123
--MyBoundary--

### 로그인 테스트
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "employeeNumber": 321654,
  "password": "ssafy123"
}

### 로그인 후 토큰으로 보호된 API 테스트
GET http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiI1IiwiZW1wbG95ZWVOdW1iZXIiOiIzMjE2NTQiLCJpYXQiOjE3NDcyMDE4MTAsImV4cCI6MTc0OTc5MzgxMH0.Q99cXys0NtzlCncTK7cVCsGcQPEaKkXTYKQvIYaSqQs

